In [1]:
import pandas as pd
import numpy as np

chas = pd.read_csv('clean_data/clean_chas.csv', dtype = {'GEOID':'string'})
soc = pd.read_csv('clean_data/clean_Soc.csv', dtype = {'GEOID':'string','STATE':'string', 'COUNTY':'string'})

In [2]:
soc_chas = (
    chas.merge(soc, on='GEOID', how='left', validate='one_to_one')
        .astype({'STATE_x':'string'})  
        .drop(columns=['STATE_y','COUNTY_y','NAME_y'])
        .rename(columns={'STATE_x':'STATE','COUNTY_x':'COUNTY','NAME_x':'NAME'})
)
soc_chas

,GEOID,STATE,COUNTY,NAME,total_households,cost_burdened_households_leq_30_percent,cost_burdened_households_30_to_50_percent,cost_burdened_households_50_to_80_percent,cost_burdened_households_all_income_levels_count,Percent_of_low_income_cb_over30_percent,...,median_nonfamily_income,poverty_rate_pct,unemployment_rate_pct,renters_cb_lt35_cnt,renters_cb_ge35_cnt,owners_cb_lt35_cnt,owners_cb_ge35_cnt,crowded_hh_pct,renter_hh_cnt,owner_hh_cnt
0,1043,1,43,Cullman,31735,1630,1605,1810,640,65.91,...,25506.0,12.69,5.01,2657,183,2487,1033,1.94,1099,1046
1,1045,1,45,Dale,19405,1605,1760,1530,700,63.00,...,26615.0,18.38,9.02,2769,350,1321,252,0.88,1455,437
2,1047,1,47,Dallas,15410,2455,1485,930,790,59.38,...,18816.0,29.22,10.38,2960,66,1234,249,1.23,1377,564
3,1049,1,49,DeKalb,26365,1810,1660,1570,580,62.91,...,21406.0,20.71,4.45,2271,67,2457,693,2.95,1406,1555
4,1051,1,51,Elmore,29795,1510,1880,1350,855,75.58,...,35766.0,10.58,4.07,2917,576,1907,1356,1.31,1286,599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,51650,51,650,Hampton,54845,6095,3765,5545,2720,81.51,...,40306.0,15.29,6.12,8380,3688,3950,4347,1.46,2651,863
3217,51660,51,660,Harrisonburg,16750,2730,1740,1835,1135,77.50,...,30732.0,25.55,4.74,3731,695,496,648,3.56,812,115
3218,51670,51,670,Hopewell,9360,1995,1145,720,250,76.17,...,25772.0,24.70,8.41,1984,253,616,355,3.13,1105,147
3219,51678,51,678,Lexington,2065,315,125,100,105,75.76,...,25323.0,22.14,3.36,361,56,157,69,0.00,32,0
3220,51680,51,680,Lynchburg,28225,3105,2445,3680,1510,74.65,...,33283.0,17.08,6.31,5361,1067,1407,971,2.42,1470,343

In [3]:
soc_chas.to_csv('clean_data/clean_soc_chas.csv', index= False)

In [3]:
print(soc_chas.isna().sum().sort_values(ascending=False))

median_nonfamily_income                             13
median_household_income                              1
Percent_of_medi_income_cb_over50_percent             1
Percent_of_low_income_cb_over50_percent              1
Percent_of_medi_income_cb_over30_percent             1
Percent_of_low_income_cb_over30_percent              1
median_family_income                                 1
GEOID                                                0
STATE                                                0
cost_burdened_households_all_income_levels_count     0
cost_burdened_households_50_to_80_percent            0
cost_burdened_households_30_to_50_percent            0
cost_burdened_households_leq_30_percent              0
Percent_of_high_income_cb_over30_percent             0
COUNTY                                               0
NAME                                                 0
total_households                                     0
Percent_of_all_with_cb_over50_percent                0
Percent_of_all_with_cb_over30_percent                0
Percent_of_high_income_cb_over50_percent             0
Percent_renter_small_family_count_cb_over30          0
Percent_owner_large_family_count_cb_over50           0
Percent_owner_small_family_count_cb_over30           0
Percent_renter_large_family_count_cb_over50          0
poverty_rate_pct                                     0
unemployment_rate_pct                                0
renters_cb_lt35_cnt                                  0
renters_cb_ge35_cnt                                  0
owners_cb_lt35_cnt                                   0
owners_cb_ge35_cnt                                   0
crowded_hh_pct                                       0
renter_hh_cnt                                        0
owner_hh_cnt                                         0
dtype: int64

In [3]:
redfin_county_data = pd.read_csv('assets\county_market_tracker.tsv000.gz', sep="\t", header=0, dtype=str)

In [5]:
redfin_county_data['PERIOD_BEGIN'] = pd.to_datetime(redfin_county_data['PERIOD_BEGIN'])
redfin_county_data['PERIOD_END'] = pd.to_datetime(redfin_county_data['PERIOD_END'])
redfin_county_data['MEDIAN_SALE_PRICE'] = redfin_county_data['MEDIAN_SALE_PRICE'].astype('float')
redfin_county_data['MEDIAN_LIST_PRICE'] = redfin_county_data['MEDIAN_LIST_PRICE'].astype('float')

In [6]:
redfin_county_data_2016_2020 = redfin_county_data[(redfin_county_data['PERIOD_BEGIN'] >= '2016-01-01') & (redfin_county_data['PERIOD_BEGIN'] <= '2020-12-31')].copy()

In [7]:
def extract_county_name(row): 
    full_county_name = row['REGION']
    if "County" in full_county_name: 
        return full_county_name.split(" County")[0]
    else: 
        return full_county_name.split(" Parish")[0]
    
    
redfin_county_data_2016_2020['COUNTY_NAME'] = redfin_county_data_2016_2020.apply(func=extract_county_name, axis=1)

In [8]:
redfin_county_data_2016_2020.columns

Index(['PERIOD_BEGIN', 'PERIOD_END', 'PERIOD_DURATION', 'REGION_TYPE',
       'REGION_TYPE_ID', 'TABLE_ID', 'IS_SEASONALLY_ADJUSTED', 'REGION',
       'CITY', 'STATE', 'STATE_CODE', 'PROPERTY_TYPE', 'PROPERTY_TYPE_ID',
       'MEDIAN_SALE_PRICE', 'MEDIAN_SALE_PRICE_MOM', 'MEDIAN_SALE_PRICE_YOY',
       'MEDIAN_LIST_PRICE', 'MEDIAN_LIST_PRICE_MOM', 'MEDIAN_LIST_PRICE_YOY',
       'MEDIAN_PPSF', 'MEDIAN_PPSF_MOM', 'MEDIAN_PPSF_YOY', 'MEDIAN_LIST_PPSF',
       'MEDIAN_LIST_PPSF_MOM', 'MEDIAN_LIST_PPSF_YOY', 'HOMES_SOLD',
       'HOMES_SOLD_MOM', 'HOMES_SOLD_YOY', 'PENDING_SALES',
       'PENDING_SALES_MOM', 'PENDING_SALES_YOY', 'NEW_LISTINGS',
       'NEW_LISTINGS_MOM', 'NEW_LISTINGS_YOY', 'INVENTORY', 'INVENTORY_MOM',
       'INVENTORY_YOY', 'MONTHS_OF_SUPPLY', 'MONTHS_OF_SUPPLY_MOM',
       'MONTHS_OF_SUPPLY_YOY', 'MEDIAN_DOM', 'MEDIAN_DOM_MOM',
       'MEDIAN_DOM_YOY', 'AVG_SALE_TO_LIST', 'AVG_SALE_TO_LIST_MOM',
       'AVG_SALE_TO_LIST_YOY', 'SOLD_ABOVE_LIST', 'SOLD_ABOVE_LIST_MOM',
       'SOLD_ABOVE_LIST_YOY', 'PRICE_DROPS', 'PRICE_DROPS_MOM',
       'PRICE_DROPS_YOY', 'OFF_MARKET_IN_TWO_WEEKS',
       'OFF_MARKET_IN_TWO_WEEKS_MOM', 'OFF_MARKET_IN_TWO_WEEKS_YOY',
       'PARENT_METRO_REGION', 'PARENT_METRO_REGION_METRO_CODE', 'LAST_UPDATED',
       'COUNTY_NAME'],
      dtype='object')

In [9]:
columns_to_keep = ['PERIOD_BEGIN', 'PERIOD_END', 'COUNTY_NAME', 'STATE', 'STATE_CODE', 'MEDIAN_SALE_PRICE', 'MEDIAN_LIST_PRICE']

In [10]:
redfin_data = redfin_county_data_2016_2020[columns_to_keep].copy()

In [11]:
redfin_data.head()

,PERIOD_BEGIN,PERIOD_END,COUNTY_NAME,STATE,STATE_CODE,MEDIAN_SALE_PRICE,MEDIAN_LIST_PRICE
2,2017-12-01,2017-12-31,Marion,Mississippi,MS,85000.0,113000.0
5,2018-01-01,2018-01-31,Scott,Indiana,IN,101700.0,135000.0
8,2018-04-01,2018-04-30,San Mateo,California,CA,1438000.0,1350000.0
13,2020-01-01,2020-01-31,Sabine,Texas,TX,358950.0,164000.0
14,2019-07-01,2019-07-31,Caledonia,Vermont,VT,120000.0,189000.0

In [6]:
redfin_latest = (
    redfin_county_data
      .sort_values("PERIOD_END")            # or PERIOD_BEGIN
      .drop_duplicates(
          subset=["STATE_CODE", "COUNTY_NAME_CLEAN"], keep="last"
      )
      [["STATE_CODE", "COUNTY_NAME_CLEAN", "MEDIAN_SALE_PRICE"]]
      .rename(columns={"MEDIAN_SALE_PRICE": "median_sale_price_2024"})
)

KeyError: Index(['COUNTY_NAME_CLEAN'], dtype='object')

In [ ]:
soc_chas_redfin = (
    soc_chas
      .merge(
          redfin_latest,
          on=["STATE_CODE", "COUNTY_NAME_CLEAN"],  # or whatever key you used
          how="left",
          validate="one_to_one"    # raises if a county duplicates
      )
)

In [ ]:

keep_cols = chas_soc.columns.tolist() + ["median_sale_price_2024"]
soc_chas_redfin = soc_chas_redfin[keep_cols]

print(soc_chas_redfin.shape)